"$schema" = 'https://starship.rs/config-schema.json'

[kubernetes]
disabled = false
symbol = '⛵ '

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>cp|p)-(?<region>[^.]+)\.braze\.com-opsadmin'
context_alias = '$name.$region [$env] ‼️'
style = 'bold red'
symbol = '📦🚨 '

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>cp|p)-(?<region>[^.]+)\.braze\.com-(?<role>.+)'
context_alias = '$name.$region [$env]'
style = 'bold red'
symbol = '📦🚨 '

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>s)-(?<region>[^.]+)\.braze\.com-opsadmin'
context_alias = '$name.$region [$env] ‼️'
style = 'bold yellow'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>s)-(?<region>[^.]+)\.braze\.com-(?<role>.+)'
context_alias = '$name.$region [$env]'
style = 'bold yellow'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>cd|d)-(?<region>[^.]+)\.braze\.com-opsadmin'
context_alias = '$name.$region [$env] ‼️'
style = 'bold green'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>cd|d)-(?<region>[^.]+)\.braze\.com-(?<role>.+)'
context_alias = '$name.$region [$env]'
style = 'bold green'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>t)-(?<region>[^.]+)\.braze\.com-opsadmin'
context_alias = '$name.$region [$env] ‼️'
style = 'bold blue'

[[kubernetes.contexts]]
context_pattern = 'k8s\.(?<name>[^.]+)\.(?<env>t)-(?<region>[^.]+)\.braze\.com-(?<role>.+)'
context_alias = '$name.$region [$env]'
style = 'bold blue'

[terraform]
format = 'via [$symbol $workspace/$version]($style) '

[time]
disabled = false